# Generated by Django 4.1.5 on 2023-07-26 17:17

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_undelete', 'Can undelete this object'),)},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.SoftDeleteUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
    ]
