# Generated by Django 4.1.5 on 2023-09-01 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('property_type', models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('home', 'Home'), ('office', 'Office'), ('building', 'Building'), ('townhouse', 'Townhouse'), ('shop', 'Shop'), ('garage', 'Garage')], db_index=True, max_length=30, null=True, verbose_name='Property Type')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
            ],
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='properties__propert_5c7790_idx'),
        ),
    ]
