# Generated by Django 4.1.5 on 2023-09-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('home', 'Home'), ('office', 'Office'), ('building', 'Building'), ('townhouse', 'Townhouse'), ('shop', 'Shop'), ('garage', 'Garage')], max_length=30, null=True, verbose_name='Property Type'),
        ),
    ]
