# Generated by Django 4.1.5 on 2023-09-01 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_property_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillaAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Property title')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description public')),
                ('surface_total', models.FloatField(blank=True, null=True, verbose_name='Surface total')),
                ('units_of_measure', models.CharField(blank=True, choices=[('square_meters', 'Square meters'), ('acres', 'Acres'), ('hectares', 'Hectares')], default='square_meters', max_length=50, null=True, verbose_name='Units of measure')),
                ('rooms_number', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=0, verbose_name='Rooms number')),
                ('bathrooms_number', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, verbose_name='Bathrooms number')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villa_attributes', to='properties.property', verbose_name='Villa attributes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TownhouseAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Property title')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description public')),
                ('surface_total', models.FloatField(blank=True, null=True, verbose_name='Surface total')),
                ('units_of_measure', models.CharField(blank=True, choices=[('square_meters', 'Square meters'), ('acres', 'Acres'), ('hectares', 'Hectares')], default='square_meters', max_length=50, null=True, verbose_name='Units of measure')),
                ('rooms_number', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=0, verbose_name='Rooms number')),
                ('bathrooms_number', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, verbose_name='Bathrooms number')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='townhouse_attributes', to='properties.property', verbose_name='Townhouse attributes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Property title')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description public')),
                ('surface_total', models.FloatField(blank=True, null=True, verbose_name='Surface total')),
                ('units_of_measure', models.CharField(blank=True, choices=[('square_meters', 'Square meters'), ('acres', 'Acres'), ('hectares', 'Hectares')], default='square_meters', max_length=50, null=True, verbose_name='Units of measure')),
                ('rooms_number', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=0, verbose_name='Rooms number')),
                ('bathrooms_number', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, verbose_name='Bathrooms number')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_attributes', to='properties.property', verbose_name='Shop attributes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Property title')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description public')),
                ('surface_total', models.FloatField(blank=True, null=True, verbose_name='Surface total')),
                ('units_of_measure', models.CharField(blank=True, choices=[('square_meters', 'Square meters'), ('acres', 'Acres'), ('hectares', 'Hectares')], default='square_meters', max_length=50, null=True, verbose_name='Units of measure')),
                ('rooms_number', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=0, verbose_name='Rooms number')),
                ('bathrooms_number', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, verbose_name='Bathrooms number')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_attributes', to='properties.property', verbose_name='Office attributes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Property title')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description public')),
                ('surface_total', models.FloatField(blank=True, null=True, verbose_name='Surface total')),
                ('units_of_measure', models.CharField(blank=True, choices=[('square_meters', 'Square meters'), ('acres', 'Acres'), ('hectares', 'Hectares')], default='square_meters', max_length=50, null=True, verbose_name='Units of measure')),
                ('rooms_number', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=0, verbose_name='Rooms number')),
                ('bathrooms_number', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, verbose_name='Bathrooms number')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_attributes', to='properties.property', verbose_name='Home attributes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GarageAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Property title')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description public')),
                ('surface_total', models.FloatField(blank=True, null=True, verbose_name='Surface total')),
                ('units_of_measure', models.CharField(blank=True, choices=[('square_meters', 'Square meters'), ('acres', 'Acres'), ('hectares', 'Hectares')], default='square_meters', max_length=50, null=True, verbose_name='Units of measure')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage_attributes', to='properties.property', verbose_name='Garage attributes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuildingAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Property title')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description public')),
                ('surface_total', models.FloatField(blank=True, null=True, verbose_name='Surface total')),
                ('units_of_measure', models.CharField(blank=True, choices=[('square_meters', 'Square meters'), ('acres', 'Acres'), ('hectares', 'Hectares')], default='square_meters', max_length=50, null=True, verbose_name='Units of measure')),
                ('rooms_number', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=0, verbose_name='Rooms number')),
                ('bathrooms_number', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, verbose_name='Bathrooms number')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_attributes', to='properties.property', verbose_name='Building attributes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApartmentAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Property title')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description public')),
                ('surface_total', models.FloatField(blank=True, null=True, verbose_name='Surface total')),
                ('units_of_measure', models.CharField(blank=True, choices=[('square_meters', 'Square meters'), ('acres', 'Acres'), ('hectares', 'Hectares')], default='square_meters', max_length=50, null=True, verbose_name='Units of measure')),
                ('rooms_number', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=0, verbose_name='Rooms number')),
                ('bathrooms_number', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, verbose_name='Bathrooms number')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_attributes', to='properties.property', verbose_name='Apartment attributes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
