# Generated by Django 4.1.5 on 2023-09-01 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_villaattributes_townhouseattributes_shopattributes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartmentattributes',
            options={'ordering': ['title'], 'verbose_name': 'Apartment attributes', 'verbose_name_plural': 'Apartments attributes'},
        ),
        migrations.AlterModelOptions(
            name='buildingattributes',
            options={'ordering': ['title'], 'verbose_name': 'Building attributes', 'verbose_name_plural': 'Buildings attributes'},
        ),
        migrations.AlterModelOptions(
            name='garageattributes',
            options={'ordering': ['title'], 'verbose_name': 'Garage attributes', 'verbose_name_plural': 'Garages attributes'},
        ),
        migrations.AlterModelOptions(
            name='homeattributes',
            options={'ordering': ['title'], 'verbose_name': 'Home attributes', 'verbose_name_plural': 'Homes attributes'},
        ),
        migrations.AlterModelOptions(
            name='officeattributes',
            options={'ordering': ['title'], 'verbose_name': 'Office attributes', 'verbose_name_plural': 'Offices attributes'},
        ),
        migrations.AlterModelOptions(
            name='shopattributes',
            options={'ordering': ['title'], 'verbose_name': 'Shop attributes', 'verbose_name_plural': 'Shops attributes'},
        ),
        migrations.AlterModelOptions(
            name='townhouseattributes',
            options={'ordering': ['title'], 'verbose_name': 'Townhouse attributes', 'verbose_name_plural': 'Townhouses attributes'},
        ),
        migrations.AlterModelOptions(
            name='villaattributes',
            options={'ordering': ['title'], 'verbose_name': 'Villa attributes', 'verbose_name_plural': 'Villas attributes'},
        ),
    ]
