# Generated by Django 4.1.5 on 2023-09-01 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_apartmentattributes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentattributes',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_attributes', to='properties.property', verbose_name='Apartment attributes'),
        ),
    ]
