# Generated by Django 4.1.5 on 2023-09-01 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_villaattributes_townhouseattributes_shopattributes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('type', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=56, verbose_name='Type')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Offer price')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='properties.property', verbose_name='Property')),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
    ]
